tweak_data.vehicle.falcogini = {}
	tweak_data.vehicle.falcogini.name = "Falcogini"
	tweak_data.vehicle.falcogini.hud_label_offset = 140
	tweak_data.vehicle.falcogini.seats = {	driver = {name = "driver", driving = true},
											passenger_front = {name = "passenger_front",driving = false,allow_shooting = true,has_shooting_mode = true,shooting_pos = Vector3(50, -20, 50)}}
	tweak_data.vehicle.falcogini.loot_points = {loot = {name = "loot"}}
	tweak_data.vehicle.falcogini.damage = {max_health = 100000000}
	tweak_data.vehicle.falcogini.max_speed = 300
	tweak_data.vehicle.falcogini.max_rpm = 12000
	tweak_data.vehicle.falcogini.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.falcogini.max_loot_bags = 100000
	tweak_data.vehicle.falcogini.interact_distance = 1000
	tweak_data.vehicle.falcogini.driver_camera_offset = Vector3(0, 0, 2.5)
	tweak_data.vehicle.falcogini.fov = 80

tweak_data.vehicle.muscle = {}
	tweak_data.vehicle.muscle.name = "Longfellow"
	tweak_data.vehicle.muscle.hud_label_offset = 150
	tweak_data.vehicle.muscle.seats = {		driver = {name = "driver", driving = true},
											passenger_front = { name = "passenger_front", driving = false, allow_shooting = true, has_shooting_mode = true, shooting_pos = Vector3(50, -20, 50)},
											passenger_back_left = { name = "passenger_back_left", driving = false, allow_shooting = true, has_shooting_mode = true},
											passenger_back_right = { name = "passenger_back_right", driving = false, allow_shooting = true, has_shooting_mode = true}
										}
	tweak_data.vehicle.muscle.loot_points = { loot_left = {name = "loot_left"},loot_right = {name = "loot_right"},loot = {name = "loot"}}
	tweak_data.vehicle.muscle.trunk_point = "trunk"
	tweak_data.vehicle.muscle.damage = {max_health = 100000000}
	tweak_data.vehicle.muscle.max_speed = 300
	tweak_data.vehicle.muscle.max_rpm = 12000
	tweak_data.vehicle.muscle.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.muscle.max_loot_bags = 100000
	tweak_data.vehicle.muscle.interact_distance = 1000
	tweak_data.vehicle.muscle.driver_camera_offset = Vector3(0, 0.2, 2.5)
	tweak_data.vehicle.muscle.fov = 80

tweak_data.vehicle.forklift = {}
	tweak_data.vehicle.forklift.name = "Forklift"
	tweak_data.vehicle.forklift.hud_label_offset = 220
	tweak_data.vehicle.forklift.seats = {	driver = {name = "driver", driving = true},
											passenger_front = {name = "passenger_front",driving = false,allow_shooting = true,has_shooting_mode = true}
										}
	tweak_data.vehicle.forklift.loot_points = {loot_left = {name = "loot"}	}
	tweak_data.vehicle.forklift.damage = {max_health = 100000000}
	tweak_data.vehicle.forklift.max_speed = 300
	tweak_data.vehicle.forklift.max_rpm = 12000
	tweak_data.vehicle.forklift.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.forklift.max_loot_bags = 100000
	tweak_data.vehicle.forklift.interact_distance = 1000
	tweak_data.vehicle.forklift.driver_camera_offset = Vector3(0, 0, 7.5)
	tweak_data.vehicle.forklift.fov = 80

tweak_data.vehicle.forklift_2 = {}
	tweak_data.vehicle.forklift_2.name = "Forklift"
	tweak_data.vehicle.forklift_2.hud_label_offset = 220
	tweak_data.vehicle.forklift_2.seats = {driver = {name = "driver", driving = true}}
	tweak_data.vehicle.forklift_2.loot_points = {loot_left = {name = "loot"}}
	tweak_data.vehicle.forklift_2.damage = {max_health = 100000000}
	tweak_data.vehicle.forklift_2.max_speed = 300
	tweak_data.vehicle.forklift_2.max_rpm = 12000
	tweak_data.vehicle.forklift_2.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.forklift_2.max_loot_bags = 100000
	tweak_data.vehicle.forklift_2.interact_distance = 1000
	tweak_data.vehicle.forklift_2.driver_camera_offset = Vector3(0, 0, 7.5)
	tweak_data.vehicle.forklift_2.fov = 80

tweak_data.vehicle.box_truck_1 = {}
	tweak_data.vehicle.box_truck_1.name = "Truck"
	tweak_data.vehicle.box_truck_1.hud_label_offset = 325
	tweak_data.vehicle.box_truck_1.seats = {	driver = {name = "driver", driving = true},
												passenger_front = {name = "passenger_front",driving = false,allow_shooting = true,has_shooting_mode = true,shooting_pos = Vector3(50, 0, 50)},
												passenger_back_left = {name = "passenger_back_left",driving = false,allow_shooting = true,has_shooting_mode = true},
												passenger_back_right = {name = "passenger_back_right",driving = false,allow_shooting = true,has_shooting_mode = true}
											}
	tweak_data.vehicle.box_truck_1.loot_points = {loot_left = {name = "loot_left"},loot_right = {name = "loot_right"}}
	tweak_data.vehicle.box_truck_1.damage = {max_health = 100000000}
	tweak_data.vehicle.box_truck_1.max_speed = 300
	tweak_data.vehicle.box_truck_1.max_rpm = 12000
	tweak_data.vehicle.box_truck_1.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.box_truck_1.max_loot_bags = 100000
	tweak_data.vehicle.box_truck_1.interact_distance = 1000
	tweak_data.vehicle.box_truck_1.driver_camera_offset = Vector3(0, 0.2, 2.5)
	tweak_data.vehicle.box_truck_1.fov = 80

tweak_data.vehicle.mower_1 = {}
	tweak_data.vehicle.mower_1.name = "Lawn Mower"
	tweak_data.vehicle.mower_1.hud_label_offset = 80
	tweak_data.vehicle.mower_1.seats = {driver = {name = "driver", driving = true}}
	tweak_data.vehicle.mower_1.loot_points = {loot_left = {name = "loot"}}
	tweak_data.vehicle.mower_1.damage = {max_health = 100000000}
	tweak_data.vehicle.mower_1.max_speed = 300
	tweak_data.vehicle.mower_1.max_rpm = 12000
	tweak_data.vehicle.mower_1.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.mower_1.max_loot_bags = 100000
	tweak_data.vehicle.mower_1.interact_distance = 1000
	tweak_data.vehicle.mower_1.driver_camera_offset = Vector3(0, 0, 3.5)
	tweak_data.vehicle.mower_1.fov = 80

tweak_data.vehicle.boat_rib_1 = {}
	tweak_data.vehicle.boat_rib_1.name = "Rib Boat"
	tweak_data.vehicle.boat_rib_1.hud_label_offset = 1
	tweak_data.vehicle.boat_rib_1.seats = {		driver = {name = "driver", driving = true},
												passenger_front = {name = "passenger_front",driving = false,allow_shooting = true,has_shooting_mode = true},
												passenger_back_left = {name = "passenger_back_left",driving = false,allow_shooting = true,has_shooting_mode = true},
												passenger_back_right = {name = "passenger_back_right",driving = false,allow_shooting = true,has_shooting_mode = true}
											}
	tweak_data.vehicle.boat_rib_1.loot_points = {loot_left = {name = "loot"}}
	tweak_data.vehicle.boat_rib_1.damage = {max_health = 100000000}
	tweak_data.vehicle.boat_rib_1.max_speed = 300
	tweak_data.vehicle.boat_rib_1.max_rpm = 12000
	tweak_data.vehicle.boat_rib_1.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.boat_rib_1.max_loot_bags = 100000
	tweak_data.vehicle.boat_rib_1.interact_distance = 1000
	tweak_data.vehicle.boat_rib_1.driver_camera_offset = Vector3(0, 0, 3.5)
	tweak_data.vehicle.boat_rib_1.fov = 80

tweak_data.vehicle.blackhawk_1 = {}
	tweak_data.vehicle.blackhawk_1.name = "Blackhawk"
	tweak_data.vehicle.blackhawk_1.hud_label_offset = 150
	tweak_data.vehicle.blackhawk_1.seats = {	driver = {name = "driver",driving = true,allow_shooting = true,has_shooting_mode = true},
												passenger_front = {name = "passenger_front",driving = false,allow_shooting = true,has_shooting_mode = true},
												passenger_back_left = {name = "passenger_back_left",driving = false,allow_shooting = true,has_shooting_mode = true},
												passenger_back_right = {name = "passenger_back_right",driving = false,allow_shooting = true,has_shooting_mode = true}
											}
	tweak_data.vehicle.blackhawk_1.loot_points = {loot_left = {name = "loot_left"},loot_right = {name = "loot_right"}}
	tweak_data.vehicle.blackhawk_1.damage = {max_health = 100000000}
	tweak_data.vehicle.blackhawk_1.max_speed = 300
	tweak_data.vehicle.blackhawk_1.max_rpm = 12000
	tweak_data.vehicle.blackhawk_1.loot_drop_point = "v_repair_engine"
	tweak_data.vehicle.blackhawk_1.max_loot_bags = 100000
	tweak_data.vehicle.blackhawk_1.interact_distance = 1000
	tweak_data.vehicle.blackhawk_1.driver_camera_offset = Vector3(0, 0, 0)
	tweak_data.vehicle.blackhawk_1.fov = 80
--[[
if not vehicle_state then return end

function vehicle_state:get_speed()
local speed = vehicle_state:get_speed() * 500
speed = speed * 500
end
]]