-- ICEAXE TWEAKS
--	tweak_data.blackmarket.melee_weapons.iceaxe = deep_clone(tweak_data.blackmarket.melee_weapons.tomahawk)
--	tweak_data.blackmarket.melee_weapons.iceaxe.name_id = "bm_melee_topaz"
--	tweak_data.blackmarket.melee_weapons.iceaxe.unit = "units/pd2_dlc_berry/weapons/rp_wpn_fps_mel_topaz2000/wpn_fps_mel_topaz2000"
--	tweak_data.blackmarket.melee_weapons.iceaxe.third_unit = "units/pd2_dlc_berry/weapons/rp_wpn_third_mel_topaz2000/wpn_third_mel_topaz2000"
--	tweak_data.blackmarket.melee_weapons.iceaxe.stats.weapon_type = "sharp"
--	tweak_data.blackmarket.melee_weapons.iceaxe.dlc = "berry"
--	tweak_data.blackmarket.melee_weapons.iceaxe.texture_bundle_folder = "berry"
--	tweak_data.blackmarket.melee_weapons.iceaxe.sounds = {}
--	tweak_data.blackmarket.melee_weapons.iceaxe.sounds.equip = "mining_pick_equip"
--	tweak_data.blackmarket.melee_weapons.iceaxe.sounds.hit_air = "mining_pick_hit_air"
--	tweak_data.blackmarket.melee_weapons.iceaxe.sounds.hit_gen = "mining_pick_hit_gen"
--	tweak_data.blackmarket.melee_weapons.iceaxe.sounds.hit_body = "mining_pick_hit_body"
--	tweak_data.blackmarket.melee_weapons.iceaxe.sounds.charge = "mining_pick_charge"
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.min_damage = 9
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.max_damage = 50
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.min_damage_effect = 2
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.max_damage_effect = 5
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.charge_time = 0.5
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.range = 500
	tweak_data.blackmarket.melee_weapons.iceaxe.stats.concealment = 50
	tweak_data.blackmarket.melee_weapons.iceaxe.expire_t = 0.10