invisible_interaction_open_axis_rvd
hospital_security_cable_green
hospital_security_cable_yellow
hospital_security_cable_red
hospital_security_cable_blue
hack_suburbia_outline
vit_take_usb_key
vit_search_clues