-- ACE TWEAKS	
--	tweak_data.blackmarket.projectiles.wpn_prj_ace = {}
--	tweak_data.blackmarket.projectiles.wpn_prj_ace.name_id = "bm_wpn_prj_ace"
--	tweak_data.blackmarket.projectiles.wpn_prj_ace.unit = "units/pd2_dlc_cake/weapons/wpn_prj_ace/wpn_prj_ace"
--	tweak_data.blackmarket.projectiles.wpn_prj_ace.unit_dummy = "units/pd2_dlc_cake/weapons/wpn_prj_ace/wpn_prj_ace_husk"
--	tweak_data.blackmarket.projectiles.wpn_prj_ace.local_unit = "units/pd2_dlc_cake/weapons/wpn_prj_ace/wpn_prj_ace_local"
--	tweak_data.blackmarket.projectiles.wpn_prj_ace.icon = "ace_projectile"
--	tweak_data.blackmarket.projectiles.wpn_prj_ace.throw_shout = true
	tweak_data.blackmarket.projectiles.wpn_prj_ace.no_cheat_count = true
	tweak_data.blackmarket.projectiles.wpn_prj_ace.impact_detonation = true
	tweak_data.blackmarket.projectiles.wpn_prj_ace.client_authoritative = true
	tweak_data.blackmarket.projectiles.wpn_prj_ace.add_trail_effect = true
	tweak_data.blackmarket.projectiles.wpn_prj_ace.throwable = true
	tweak_data.blackmarket.projectiles.wpn_prj_ace.dlc = "pd2_clan"
	tweak_data.blackmarket.projectiles.wpn_prj_ace.max_amount = 1337
	tweak_data.blackmarket.projectiles.wpn_prj_ace.anim_global_param = "projectile_four"
	tweak_data.blackmarket.projectiles.wpn_prj_ace.throw_allowed_expire_t = 0.10
	tweak_data.blackmarket.projectiles.wpn_prj_ace.expire_t = 1.0
	tweak_data.blackmarket.projectiles.wpn_prj_ace.repeat_expire_t = 0.01