-- FRAG GRENADE TWEAKS
	tweak_data.weapon.grenades										=	{}				--	Default	=
	tweak_data.weapon.grenades.frag									=	{}				--	Default	=
	tweak_data.weapon.grenades.frag.damage							=	500				--	Default	=	30
	tweak_data.weapon.grenades.frag.player_damage					=	0				--	Default	=	10
	tweak_data.weapon.grenades.frag.range							=	5000			--	Default	=	1000
	tweak_data.weapon.grenades.launcher_frag						=	{}				--	Default	=
	tweak_data.weapon.grenades.launcher_frag.damage					=	500				--	Default	=	34
	tweak_data.weapon.grenades.launcher_frag.curve_pow				=	5				--	Default	=	0.1
	tweak_data.weapon.grenades.launcher_frag.player_damage			=	0				--	Default	=	8
	tweak_data.weapon.grenades.launcher_frag.range					=	3000			--	Default	=	350
	tweak_data.weapon.grenades.launcher_frag.init_timer				=	0.5				--	Default	=	2.5
	tweak_data.weapon.grenades.launcher_frag.mass_look_up_modifier	=	2				--	Default	=	1
	tweak_data.weapon.grenades.launcher_frag.sound_event			=	"gl_explode"	--	Default	=